LIBRARIES_STATIC            = 
PROGRAMS                    = printdouble doublerepresentation

GLOBAL_CFLAGS               = -O3 -flto -pthread -pipe -Wall -ggdb -std=gnu99 -fms-extensions -Iinclude -Wmissing-prototypes -Wno-uninitialized -Wstrict-prototypes
#GLOBAL_CFLAGS               = -O0 -pthread -pipe -Wall -ggdb -std=gnu99 -fms-extensions -Iinclude -Wmissing-prototypes -Wno-uninitialized -Wstrict-prototypes
GLOBAL_LDFLAGS              = -lm

### LIBRARIES #################################################################


### PRINTDOUBLE ###############################################################

printdouble_CFLAGS          = 
printdouble_LDFLAGS         = 
printdouble_LIBRARIES       = 
printdouble_SOURCE          = main.c


doublerepresentation_CFLAGS          = 
doublerepresentation_LDFLAGS         = 
doublerepresentation_LIBRARIES       = 
doublerepresentation_SOURCE          = doublerepresentation.c


include autogen.mk
