LIBRARIES_STATIC            = 
PROGRAMS                    = project2

GLOBAL_CFLAGS               = -O0 -pthread -pipe -Wall -ggdb -std=gnu99 \
                              -fms-extensions -Iinclude -Wmissing-prototypes \
                              -Wno-uninitialized -Wstrict-prototypes
GLOBAL_LDFLAGS              = -lm

### LIBRARIES #################################################################


### PROJECT2 ##################################################################

project2_CFLAGS          = 
project2_LDFLAGS         = 
project2_LIBRARIES       = 
project2_SOURCE          = project2.c \
                           print.c


include autogen.mk
